spring:
  application:
    name: auth-server
  config:
    import: optional:classpath:/config/application.yaml
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000
        client:
          frontend-client:
            registration:
              client-id: frontend-client
              client-authentication-methods:
                - none
              authorization-grant-types:
                - authorization_code
              redirect-uris:
                - http://localhost:5173
              post-logout-redirect-uris:
                - http://localhost:5173
              scopes:
                - openid
                - profile
                - email
            require-proof-key: true

server:
  port: 9000
  servlet:
    context-path: /

app:
  security:
    users:
      - username: admin
        password: admin
        roles:
          - USER
          - ADMIN
